// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA17cKC0-Bvtr0TSJSLhBmwjHJ8Mgt6OuM',
    appId: '1:573413174523:web:c575ffc9ede1d96813545e',
    messagingSenderId: '573413174523',
    projectId: 'movers-96426',
    authDomain: 'movers-96426.firebaseapp.com',
    storageBucket: 'movers-96426.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiWrW4VYKQ1ERy0p6SM6rd_d1SvZduxo4',
    appId: '1:573413174523:android:a52b796c93f7bbff13545e',
    messagingSenderId: '573413174523',
    projectId: 'movers-96426',
    storageBucket: 'movers-96426.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp74Au9OvIcydiRDNl5skauvoXMV8rEk0',
    appId: '1:573413174523:ios:c9a7c1c699f1dddd13545e',
    messagingSenderId: '573413174523',
    projectId: 'movers-96426',
    storageBucket: 'movers-96426.firebasestorage.app',
    iosBundleId: 'com.example.vanick',
  );
}
